### ISSUE TITLE
Problem upgrading from previous horizontal version

### ISSUE THREAD

**Issue by FulvioSpelta** [Guizz27/DWIN_LK4Pro#15]
**Describe the bug**
I've update my U30 Pro display starting from an horizontal version. The result is that the bitmap are "portrait" but all other references such as message positioning, temperature positioning in home screen and button are "landscape". See attached images (during upgrade and the home after upgrade):

![image](https://user-images.githubusercontent.com/1832999/170325155-56338f05-210a-4a85-983f-92e16df4cc6e.png)
![image](https://user-images.githubusercontent.com/1832999/170325415-dc5d0149-3cad-4df5-be90-7d6e5214e6fc.png)

**To Reproduce**
Upgrade fw from a horizontal version (I've done the upgrade more times)

**Expected behavior**
Full portrait

**Comment by FulvioSpelta** [comment]
**Workaround**

I've installed the original Alfawise display fw (that is vertical looking) and that package has rotated the configuration of the display, further i've installed this fw and it's all ok.
![image](https://user-images.githubusercontent.com/1832999/170373032-f41385dc-69f1-4171-9398-a9d710cccd78.png)
![image](https://user-images.githubusercontent.com/1832999/170373097-f3c34365-18aa-45cc-bc27-713da4df5430.png)

**Comment by Guizz27** [comment]
Hi @FulvioSpelta, thanks a lot for investigating and finding a workaround. I will look to include the file T5UID1.CFG in a near future.

**Comment by Guizz27** [comment]
I now include the file T5UID1_reset90.CFG which will reset the orientation and will also erase previous data in memory to make sure there is nothin left that could interfere with this firmware.
