### ISSUE TITLE
No beep sound on filament tab

### ISSUE THREAD

**Issue by jehendeoff** [Guizz27/DWIN_LK4Pro#18]
**Describe the bug**
the screen does not beep when clicking "filament"

**Comment by Guizz27** [comment]
Thank you, it will be fixed in next release. I don't have a speaker in my screen so I didn't notice it. I saw in the code there were other places where the beep was missing like in advanced settings.

**Comment by loroff** [comment]
> **Describe the bug** the screen does not beep when clicking "filament"

bonsoir je n ai pas de haut parleur sur mon ecran de ma lk4 pro pouvez vous me donner le model de ce dernier svp merci

**Comment by Guizz27** [comment]
Je n'ai pas de haut parleur non plus sur mon écran. Je ne trouve pas de haut parleur avec la bonne connexion. Il faudrait probablement acheter un buzzer 5v et lui ajouter une connexion JST de la bonne taille.

**Comment by loroff** [comment]
bonjour merci de votre reponse j ai justement des buzzer 5v je vais regarder pour un connecteur

**Comment by loroff** [comment]
bon je confirme qu avec un buzzer passif de 5 v cela marche parfaitement

**Comment by Guizz27** [comment]
Super!
