### ISSUE TITLE
After adjusting fan settings while printing, unable to exit input screen.

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/DWIN_LK4Pro#19]
Sometimes after adjusting the fan settings while printing, screen freezes and you are unable to exit the screen or make any further adjustments.

**Comment by Guizz27** [comment]
I could not reproduce it. Let me know if you find a way to reproduce it.

**Comment by jgbrown54** [comment]
I was also unsuccessful at reproducing this.
