### ISSUE TITLE
Gcode(screen) not working

### ISSUE THREAD

**Issue by darky552435** [Guizz27/DWIN_LK4Pro#8]
after trying to use gcode on screen its said update to dwin gui\os. i dont see anything then google it, can u say what i should do

**Comment by darky552435** [comment]
also forgot to mention that auto home isnt work then i press start. bltouch is working

**Comment by Guizz27** [comment]
where did it say to update the dwin gui\os ? Is it possible to attach a picture of the message?
Which gcode command did you try to run?

**Comment by darky552435** [comment]
btw i cant even run 1 gcode command or even write it. 
happen then i click gcode icone
https://pin.it/2HI0xsM

**Comment by Guizz27** [comment]
Thank you for the picture and the explanations. It looks like your OS in the screen firmware is an old version.

You can check your gui and os version but going into Settings then About. Then tap 10 times anywhere on the screen, this should display a screen with the version numbers. GUI should be at least version 48 and OS should be at least version 33. See attached picture as a reference.

Download the 2 .BIN files from here https://github.com/Guizz27/DWIN_LK4Pro/tree/main/extras/core_firmware
Add them to the DWIN_SET folder on your SD card, then follow the same procedure as before to upgrade the screen firmware. This will install a newer OS on the screen. You only need to update these once, so remove them from the SD card when done.

Please note that this is not a process I had to do before. I'm just giving you the instructions I found on Desuuu github https://github.com/Desuuuu/DGUS-reloaded/wiki/Flashing-the-T5-GUI-and-OS-firmware. 

Let me know how it goes and if it fixes the issue. 



![20211211_220244](https://user-images.githubusercontent.com/15663690/145698744-3ebcc02e-b3c9-41c1-a4b1-78040267f112.jpg)

**Comment by darky552435** [comment]
well, now its working, thank u so much (for testing run g28,29)
