### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jgbrown54** [Guizz27/DWIN_LK4Pro#9]
This is more of a question than an issue.

A friend tried to update but he couldn't get the DWIN_SET to load so he fell back. He said he had to use .TFT files. He is currently on 0.3.2-DWTJ. Does that make sense?

**Comment by jgbrown54** [comment]
When we try to update on a display showing 0.3.1-DW, using DWIN_SET, it doesn't update. The old screens remain.
![image](https://user-images.githubusercontent.com/65692185/163516885-29153acb-1ea4-4458-89ed-8c71e166e117.png)

**Comment by jgbrown54** [comment]
I finally figured this out. Both of these systems were running Windows 11 Home Edition. It does not allow formatting an SD card with an Allocation unit of 4096. I had them go into a command prompt and enter -- >Format D: /FS:FAT32 /Q /A:4096 where D: is the drive where the SD card is mounted.

**Comment by Guizz27** [comment]
Good catch about Windows 11. 
Did it work for your friend with a DWTJ screen firmware after formatting the SD card correctly? I'm curious because that format uses a tft file but maybe it also support a DWIN_SET folder.

**Comment by jgbrown54** [comment]
I do not know. The guy that used the .tft file, went back to the old FW and he was ticked that he went through all the trouble to load the new FW and it didn't work.

**Comment by jgbrown54** [comment]
Sorry to reopen this in the issues section. I'm new to Github and I don't see anywhere to ask questions.

The guy that had the DWTJ tried again and made sure that he had the SD formatted properly. It still wouldn't load the DWIN_SET. Couold he maybe load the TFT files from here? What is the process to load the TFT files?

I have been helping people on the Longer3d Facebook page load your firmware and screens. Most just have issues following instructions.

**Comment by Guizz27** [comment]
I don't know much more about how Github works for issues and comments either.

I don't have a TFT file and I don't know how to produce one. I'm afraid that only people with a DW screen (either no letter after the screen fw version like 0.3.1 or the letters DW like 0.3.1DW) will be able to use the firmware from here.

My guess is the OS on the screen has to be updated but this is just a guess. I have the OS here https://github.com/Guizz27/DWIN_LK4Pro/tree/main/extras/core_firmware that could be used to update the OS on the screen and then accept the DWIN_SET folder. Again, this is a guess. I would not recommend the guy to update the OS unless he has a copy of the original that he can put back.

BTW, thanks for helping people, this is very appreciated.

**Comment by Guizz27** [comment]
People who have a DW screen and can't enter gcode commands on the screen have to update the OS by copying the 2 files from the link above to the DWIN_SET folder on the SD card. More detailed instructions here: https://github.com/Desuuuu/DGUS-reloaded/wiki/Flashing-the-T5-GUI-and-OS-firmware

**Comment by jgbrown54** [comment]
The guy that had the 0.3.2-DWTJ display just blew up his motherboard. So he going to a different motherboard screen combo. He has offered me his old screen for nothing. It will give me a chance to see if I can figure out a solution. Would it be possible to get an email or messenger address for you or should I just keep opening this issue. I promise not abuse it but I might have some questions. Should I add the files mentioned above to the DWIN_SET that I am providing to everyone or just for people having issues entering gcodes?

**Comment by Guizz27** [comment]
The 2 files should only be added for people with issues. When you get the DWTJ screen you can try to add those 2 files to see if it will help.
To keep asking questions you can try the "Discussions" tab at the top in GitHub. I enabled it. Not sure how it works. I think it can help to keep discussions in github for future reference and reference by other people.

I will PM you on messenger, so you can also contact me as well for very specific things.

**Comment by Guizz27** [comment]
Closing this issue. We learned about the SD format parameters and we now know that T5L, DWJT and DWJTB screens cannot be upgraded.

**Comment by Gilgul46** [comment]
> Closing this issue. We learned about the SD format parameters and we now know that T5L, DWJT and DWJTB screens cannot be upgraded.

Why can't they be updated? What did you learn about the SD format parameters that made you come to the conclusion that T5L, DWJT and DWJTB screens cannot be upgraded?
Also, do you know where can I get the DW screen? If I can't update mine, I just have to replace the screen, but I can't really find clearly where to buy it 😅

**Comment by Guizz27** [comment]
For the upgrade to work on the DW screen, the SD card should be max 16GB and be formatted in FAT32 with 4K cluster size.
To upgrade a non-DW screen, I need to use a different software to create the firmware as the file format is not compatible between those screens. Since I only own a DW, I cannot develop and test for other screens.

The screen you want is DMT48270C043_06WT. There is one on aliexpress https://www.aliexpress.com/item/4000957547147.html?spm=a2g0o.cart.0.0.9a6338daJB8zaz&mp=1 (has to be 06WT) but it does not come with the white connector on the back. You could probably use the one from the screen you have if you can unsolder it and solder it to the new screen.

James Brown (@jgbrown54 )  sometimes has DW screens that he sells with the white connector.

**Comment by Gilgul46** [comment]
DUDE THANK YOU SO MUCH!!!!
I really appreciate everything, and if you're in Europe I can send you my current screen, so you can work on it if you wanna xd 
I already gotta buy a new one, so I don't really mind giving you my current one hahaha, especially to the guy who works on this cool updates for the Longer LK4 pro (and I use bl-touch too hahaha) ;)

**Comment by Gilgul46** [comment]
> For the upgrade to work on the DW screen, the SD card should be max 16GB and be formatted in FAT32 with 4K cluster size. To upgrade a non-DW screen, I need to use a different software to create the firmware as the file format is not compatible between those screens. Since I only own a DW, I cannot develop and test for other screens.
> 
> The screen you want is DMT48270C043_06WT. There is one on aliexpress https://www.aliexpress.com/item/4000957547147.html?spm=a2g0o.cart.0.0.9a6338daJB8zaz&mp=1 (has to be 06WT) but it does not come with the white connector on the back. You could probably use the one from the screen you have if you can unsolder it and solder it to the new screen.
> 
> James Brown (@jgbrown54 ) sometimes has DW screens that he sells with the white connector.

DUDE THANK YOU SO MUCH!!!!
I really appreciate everything, and if you're in Europe I can send you my current screen, so you can work on it if you wanna xd
I already gotta buy a new one, so I don't really mind giving you my current one hahaha, especially to the guy who works on this cool updates for the Longer LK4 pro (and I use bl-touch too hahaha) ;)

**Comment by Guizz27** [comment]
HaHa! I'm in Canada :).
Looking at the pictures of your screen, the white connector would not work on the DW screen because you have 4 pins and the DW has 6 pins with only 4 used but the used ones are not consecutives. So you need to replace the plug on the cable as well.

**Comment by Gilgul46** [comment]
> HaHa! I'm in Canada :). Looking at the pictures of your screen, the white connector would not work on the DW screen because you have 4 pins and the DW has 6 pins with only 4 used but the used ones are not consecutives. So you need to replace the plug on the cable as well.

DUDE I GOT SO LUCKY, LOOK: https://www.ebay.es/itm/115618664377?mkcid=16&mkevt=1&mkrid=1185-127638-7840-0&ssspo=eMhAl0lETbK&sssrc=2349624&ssuid=cO_U2_dhSmi&var=&widget_ver=artemis&media=WHATS_APP 
It's that right??? PLUS THE CABLE HELL YEA!!

**Comment by Guizz27** [comment]
Yes that's the right thing!!

**Comment by Gilgul46** [comment]
Hey @Guizz27, just wanted to tell you that after doing some things with Proterface it told me that the old screen is DWIN-T5, and after a simple search I found this GitHub rep: https://github.com/ihrapsa/T5UIC1-DWIN-toolset. I don't know if it helps you in any way, but I hope it does :)

**Comment by Guizz27** [comment]
Thanks for the link. I will take a look.
T5 is the same one I have. Is the "old screen"  the used one from ebay or the original one that came with the printer? If you have the original screen dismounted, could you take a picture of the back showing any number that could look like a model number including the chips models?

**Comment by Gilgul46** [comment]
The "old" screen is the newer version, aka the 4 letter combination
version. The Ebay screen is still in shipping, but I'll unmount my current
one and send pics!

I found it curious that pronterface says the new sort of screens is a DWIN
T5

**Comment by Gilgul46** [comment]
Hello! 
The screen got lost in shipping and I wanna cry, but here's the screen :)
![20230407_122708](https://user-images.githubusercontent.com/55161820/230593604-8d945fb3-eaf2-4fe0-ac1b-248a430d0021.jpg)

**Comment by Gilgul46** [comment]
> Thanks for the link. I will take a look. T5 is the same one I have. Is the "old screen" the used one from ebay or the original one that came with the printer? If you have the original screen dismounted, could you take a picture of the back showing any number that could look like a model number including the chips models?

Here is also a pic of a zoom on the chips:
![20230407_123127](https://user-images.githubusercontent.com/55161820/230593975-dff65b66-969d-4edf-84b5-061ef82e8fef.jpg)
If you want any other pics, tell me! :)

**Comment by Gilgul46** [comment]
Here it is from the back: 
![20230407_123512](https://user-images.githubusercontent.com/55161820/230594489-f7b0cba2-1c96-4543-99b8-f56a0bcefb55.jpg)

**Comment by Gilgul46** [comment]
Here it is from the back: 
![20230407_123512](https://user-images.githubusercontent.com/55161820/230595252-90bcb481-3078-4ab8-b291-89df51e306b0.jpg)


And another pic just in case:
![20230407_124021](https://user-images.githubusercontent.com/55161820/230595216-ccfe6841-403f-489e-a8b7-4d52f57eb6f7.jpg)

**Comment by Gilgul46** [comment]
After reverse image search in AliExpress it looks like this:
€ 14.68 | New listing TJC4827X243_011 X2 series 4.3 inch IPS HMI serial screen resistive touch LCD display human-computer interaction
https://a.aliexpress.com/_Ewa1OLN

**Comment by Gilgul46** [comment]
> Thanks for the link. I will take a look. T5 is the same one I have. Is the "old screen" the used one from ebay or the original one that came with the printer? If you have the original screen dismounted, could you take a picture of the back showing any number that could look like a model number including the chips models?

Hello! any way I can help?

**Comment by Gilgul46** [comment]
I still didn't receive a response regarding everything haaha

**Comment by Guizz27** [comment]
Sorry, your screen is not supported at this time. You have a TJC... screen and the chip says T7. The link you reference on aliexpress may be the same as the one you have or very similar.

The good news is the cable for your screen is a 6 pin connector.  If you buy the one on aliexpress from the link I gave you and you can unsolder/solder the connector from your old screen it would work.

If you are not comfortable to solder the connector, I can order the screen, install a connector and ship it to you but it would cost at least $30 US + shipping to you which could end up cost you about $45 US total or even more depending where you are.

**Comment by Gilgul46** [comment]
Thanks for the offer, but I ended up doing it myself and HOLLY MOLLY IT'S SO MUCH BETTER THAN STOCK. Like, finally, I don't need my computer whenever I want to calibrate the BL-Touch, or input any specific short G-code!!!! thanks so much, truly!!! I just hope you'll be able to make it so anyone with any screen can enjoy it one day :)
